### ISSUE TITLE
CCL Error on a Thermaldynamics:Duct

### ISSUE THREAD

**Issue by Issacozzman** [FTBTeam/FTB-Builders-Paradise#57]
CCL has caught an exception whilst rendering a block BlockPos: x:-337, y:68, z:-2791 Block Class: class cofh.thermaldynamics.block.BlockDuct Registry Name: thermaldynamics:duct_0 Metadata: 0 State: thermaldynamics:duct_0[meta=0] Tile at position Tile Class: class cofh.thermaldynamics.duct.tiles.TileDuctEnergy$Basic Tile Id: thermaldynamics:duct_energy_basic Tile NBT: {Covers:[{side:4,meta:0b,block:"minecraft:brick_block"}],Energy:{},x:-337,y:68,z:-2791,id:"thermaldynamics:duct_energy_basic",Attachments:[]} You can turn off player messages in the CCL config file. java.lang.ArrayIndexOutOfBoundsException: 5 at net.minecraftforge.client.model.pipeline.VertexLighterFlat.processQuad(VertexLighterFlat.java:237) at net.minecraftforge.client.model.pipeline.QuadGatheringTransformer.put(QuadGatheringTransformer.java:66) at codechicken.lib.render.CCQuad.pipe(CCQuad.java:240) at cofh.thermaldynamics.duct.attachments.cover.CoverRenderer.renderBlockQuads(CoverRenderer.java:78) at cofh.thermaldynamics.duct.attachments.cover.CoverRenderer.renderBlockCover(CoverRenderer.java:148) at cofh.thermaldynamics.duct.attachments.cover.Cover.render(Cover.java:128) at cofh.thermaldynamics.render.RenderDuct.renderBlock(RenderDuct.java:378) at codechicken.lib.render.block.BlockRenderingRegistry.renderBlock(BlockRenderingRegistry.java:94) at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:69) at com.elytradev.architecture.client.render.CustomBlockDispatcher.func_175018_a(CustomBlockDispatcher.java:98) at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:328) at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100) at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43) at java.lang.Thread.run(Thread.java:745)

**Comment by EKataskin** [comment]
I have the same error:

java.lang.ArrayIndexOutOfBoundsException: 5
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.processQuad(VertexLighterFlat.java:237) ~[VertexLighterFlat.class:?]
	at net.minecraftforge.client.model.pipeline.QuadGatheringTransformer.put(QuadGatheringTransformer.java:66) ~[QuadGatheringTransformer.class:?]
	at codechicken.lib.render.CCQuad.pipe(CCQuad.java:240) ~[CCQuad.class:?]
	at cofh.thermaldynamics.duct.attachments.cover.CoverRenderer.renderBlockQuads(CoverRenderer.java:78) ~[CoverRenderer.class:?]
	at cofh.thermaldynamics.duct.attachments.cover.CoverRenderer.renderBlockCover(CoverRenderer.java:148) ~[CoverRenderer.class:?]
	at cofh.thermaldynamics.duct.attachments.cover.Cover.drawSelectionExtra(Cover.java:234) ~[Cover.class:?]
	at cofh.thermaldynamics.proxy.EventHandlerClient.doAttachmentHighlight(EventHandlerClient.java:78) ~[EventHandlerClient.class:?]
	at cofh.thermaldynamics.proxy.EventHandlerClient.onBlockHighlight(EventHandlerClient.java:54) ~[EventHandlerClient.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2132_EventHandlerClient_onBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:191) [ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:680) [Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1819) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by EKataskin** [comment]
[crash-2019-07-17_22.00.22-client.txt](https://github.com/FTBTeam/FTB-Builders-Paradise/files/3403405/crash-2019-07-17_22.00.22-client.txt)
[crash-2019-07-17_22.00.22-server.txt](https://github.com/FTBTeam/FTB-Builders-Paradise/files/3403406/crash-2019-07-17_22.00.22-server.txt)

**Comment by Sunekaer** [comment]
Please report to the mod author, i cant do anything about these
